// Regenerates assets/js/icons.js from the lucide-static package:
//   npm pack lucide-static && tar -xzf lucide-static-*.tgz
//   node scripts/icons.mjs package/icons
import fs from 'node:fs';
import path from 'node:path';
const SRC = process.argv[2];
if (!SRC) { console.error('Usage: node scripts/icons.mjs <lucide-static>/icons'); process.exit(1); }
// emoji used in the UI → Lucide icon
const EMOJI={'🚐':'caravan','🛏':'bed-double','💺':'armchair','⚙️':'cog','⚙':'cog','🚿':'shower-head','🚽':'toilet','🍳':'cooking-pot','🧊':'refrigerator','❄️':'snowflake','🔥':'flame','☀️':'sun','🔌':'plug-zap','📶':'wifi','🚲':'bike','👶':'baby','🐾':'paw-print','🪑':'armchair','💧':'droplets','⛺':'tent','📍':'map-pin','🗺':'map','🗺️':'map','🗓':'calendar-days','📅':'calendar-days','💬':'message-circle','🔒':'lock','🛡️':'shield-check','🪪':'id-card','⚡':'zap','💳':'credit-card','👨‍👩‍👧':'users','🎉':'party-popper','📄':'file-text','🧪':'flask-conical','🧭':'compass','📋':'clipboard-list','📎':'paperclip','📞':'phone','🔔':'bell','📱':'smartphone','🏦':'landmark','🧳':'luggage','⬇':'download','🏠':'house','⚖️':'scale','📈':'chart-line','🔎':'search','🔍':'search','🔧':'wrench','🔐':'lock-keyhole','🧾':'receipt','👥':'users','📜':'scroll-text','❓':'circle-help','↩️':'undo-2','🚨':'siren','✉️':'mail','ℹ️':'info','🚀':'rocket','💰':'wallet','📷':'camera','🧰':'toolbox','🛣':'route','🕑':'clock','✈️':'plane','✨':'sparkles','⏳':'hourglass','⚠️':'triangle-alert','⚠':'triangle-alert','↗':'share','↻':'refresh-cw','♡':'heart','✕':'x','✓':'check','★':'star'};
const extra=['languages','star','chevron-left','chevron-right','arrow-right','fuel','gauge','mountain','navigation','umbrella','car','info','sliders-horizontal','list','heart','x','check','user','log-out','menu','shield','camera','image','plus','minus','filter'];
const names=[...new Set([...Object.values(EMOJI),...extra])].sort();
const out={};
for(const n of names){
  const f=path.join(SRC,n+'.svg'); if(!fs.existsSync(f)){ console.error('MISSING',n); continue; }
  const svg=fs.readFileSync(f,'utf8'); const inner=svg.slice(svg.indexOf('>',svg.indexOf('<svg'))+1, svg.lastIndexOf('</svg>')).replace(/\s*\n\s*/g,'').replace(/\s+\/>/g,'/>').trim();
  out[n]=inner;
}
const js=`/*
 * Icons: a subset of Lucide (https://lucide.dev), ISC License,
 * Copyright (c) Lucide Icons and Contributors. Generated by scripts/icons.mjs.
 * App.icon('bed-double') returns an inline SVG that takes the text colour and size.
 */
(() => {
const ICONS = ${JSON.stringify(out,null,0).replace(/","/g,'",\n  "').replace(/^\{/,'{\n  ').replace(/\}$/,'\n}')};
// Emoji that older data or content may still contain, mapped to icons
App.EMOJI_ICONS = ${JSON.stringify(EMOJI)};
App.icon = (name, { size, label, cls = '' } = {}) => {
  const body = ICONS[name] || ICONS[App.EMOJI_ICONS[name]];
  if (!body) return App.h\`\${name}\`;
  const a11y = label ? \`role="img" aria-label="\${App.esc(label)}"\` : 'aria-hidden="true" focusable="false"';
  return new App.SafeHTML(\`<svg class="ic \${cls}" viewBox="0 0 24 24" \${size ? \`width="\${size}" height="\${size}"\` : ''} fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" \${a11y}>\${body}</svg>\`);
};
App.hasIcon = (name) => !!(ICONS[name] || ICONS[App.EMOJI_ICONS[name]]);
})();
`;
fs.writeFileSync('assets/js/icons.js',js);
console.log(Object.keys(out).length,'icons', Buffer.byteLength(js),'bytes');
